import WMTS from 'ol/source/WMTS';
import { geoserverApiUrl } from '../config/constants';

const baseMapLayers = [
  {
    name: 'osm',
    title: 'Схема',
    className: 'osm',
    link: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution: 'gd',
    type: 'osm',
    labelsLayer: 'lightAnno',
  },

  // {
  //   name: '2gis',
  //   className: '2gis',
  //   title: 'Спутник',
  //   link: 'https://tile{s}.maps.2gis.com/tiles?x={x}&y={y}&z={z}',
  //   attribution: '',
  //   type: 'xyz',
  //   css: 'GeoCartographicSwitcher__img__satellite',
  // },
  {
    name: 'satellite',
    className: 'satellite',
    title: 'Спутник',
    // title: 'Росреестр ПКК',
    link: 'https://tile{s}.maps.2gis.com/tiles?x={x}&y={y}&z={z}',
    attribution: '',
    labelsLayer: '',
  },
  {
    name: 'hybrid',
    className: 'satellite',
    title: 'Гибрид',
    // title: 'Росреестр ПКК',
    link: 'https://tile{s}.maps.2gis.com/tiles?x={x}&y={y}&z={z}',
    attribution: '',
    labelsLayer: 'darkAnno',
  },

  {
    name: 'rosreestr',
    className: 'osm',
    title: 'ЕЭКО',
    link: 'https://tile{s}.maps.2gis.com/tiles?x={x}&y={y}&z={z}',
    attribution: '',
    labelsLayer: '',
    //labelsLayer: 'lightAnno',
  },
];

//---------WFS------

const wfsHoverLayers = [
  {
    name: 'old_lyr_wfs_1z_road_>40_mln',
    title: '>40mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: undefined,
    maxZoom: undefined, //8.6,
    style: { color: 'rgba(184,184,184, 0.01)', width: 15 },
    //style: { color: 'black', width: 10 },
  },
  {
    name: 'old_lyr_wfs_2z_road_40_2_mln',
    title: '40mln-2mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 8.6,
    maxZoom: undefined, //9.4,
    style: { color: 'rgba(184,184,184, 0.01)', width: 15 },
    //style: { color: 'red', width: 8 },
  },
  {
    name: 'old_lyr_wfs_2z_road_100_min',
    title: '100 000 - 2 000 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 9.4,
    maxZoom: undefined, //12.6,
    style: { color: 'rgba(184,184,184, 0.01)', width: 15 },
    //style: { color: 'green', width: 6 },
  },
  {
    name: 'old_lyr_wfs_2z_road_2000_min',
    title: '100 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 12.6,
    maxZoom: undefined,
    style: { color: 'rgba(184,184,184, 0.01)', width: 15 },
    //style: { color: 'blue', width: 5 },
  },
];

// road: ["#ce7b2b", "#e19b3c", "#f5bb4f"],
// skeleton: ["#002d70", "#0f51c1", "#578df1"]

const wfsLayers = [
  {
    name: 'zoom_1_roads',
    title: '>40mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 0,
    maxZoom: 7,
    visible: true,
    layersType: 'road',
    style: {
      id: [83717],
      width: 10,
      color: 'rgba(184,184,184, 0.01)',
      //widths: [5],
      widths: [10],
      //colors: ['#ce7b2b'],
      colors: ['rgba(184,184,184, 0.01)'],
    },
    selectedWidth: 12,
    selected: true,
    zoomSource: 'zoom_1',
    //zoomSource: 'road_1',
    source: 'zoom_1_roads',
  },
  {
    name: 'zoom_2_roads',
    title: '40mln-2mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 7,
    maxZoom: 9,
    visible: true,
    layersType: 'road',
    style: {
      id: [83717, 83718, 83719],
      width: 8,
      color: 'rgba(184,184,184, 0.01)',
      //widths: [4, 2, 2],
      widths: [8, 8, 8],
      //colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
      colors: ['rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)'],
    },
    selectedWidth: 11,
    selected: true,
    zoomSource: 'zoom_2',
    //zoomSource: 'road_2',
    source: 'zoom_2_roads',
  },
  {
    name: 'zoom_3_roads',
    title: '100 000 - 2 000 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 9,
    maxZoom: 13, //12.6,
    visible: true,
    layersType: 'road',
    style: {
      id: [83717, 83718, 83719],
      width: 8,
      color: 'rgba(184,184,184, 0.01)',
      //widths: [7, 3, 2],
      widths: [8, 8, 8],
      //colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
      colors: ['rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)'],
    },
    selectedWidth: 10,
    selected: true,
    zoomSource: 'zoom_3',
    //zoomSource: 'road_3',
    source: 'zoom_3_roads',
  },
  {
    name: 'zoom_4_roads',
    title: '100 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 13,
    maxZoom: 19,
    visible: true,
    layersType: 'road',
    style: {
      id: [83717, 83718, 83719],
      width: 5,
      color: 'rgba(184,184,184, 0.01)',
      //widths: [11, 9, 5],
      widths: [6, 6, 6],
      //colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
      colors: ['rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)', 'rgba(184,184,184, 0.01)'],
    },
    selectedWidth: 10,
    selected: true,
    zoomSource: 'zoom_4',
    //zoomSource: 'road_4',
    source: 'zoom_4_roads',
  },
  {
    name: 'zoom_1_skeleton',
    title: '>40mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 0,
    maxZoom: 7,
    visible: false,
    layersType: 'skeleton',
    style: {
      id: [83717],
      width: 5,
      color: 'black',
      widths: [5],
      colors: ['#002d70'],
    },
    selectedWidth: 12,
    selected: true,
    zoomSource: 'zoom_1',
    //zoomSource: 'road_1',
    source: 'zoom_1_skeleton',
  },
  {
    name: 'zoom_2_skeleton',
    title: '40mln-2mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 7,
    maxZoom: 9,
    visible: false,
    layersType: 'skeleton',
    style: {
      id: [83717, 83718, 83719],
      width: 6,
      color: 'red',
      widths: [4, 2, 2],
      colors: ['#002d70', '#0f51c1', '#578df1'],
    },
    selectedWidth: 10,
    selected: true,
    zoomSource: 'zoom_2',
    //zoomSource: 'road_2',
    source: 'zoom_2_skeleton',
  },
  {
    name: 'zoom_3_skeleton',
    title: '100 000 - 2 000 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 9,
    maxZoom: 13, //12.6,
    visible: false,
    layersType: 'skeleton',
    style: {
      id: [83717, 83718, 83719],
      width: 11,
      color: 'green',
      widths: [7, 3, 2],
      colors: ['#002d70', '#0f51c1', '#578df1'],
    },
    selectedWidth: 9,
    selected: true,
    zoomSource: 'zoom_3',
    //zoomSource: 'road_3',
    source: 'zoom_3_skeleton',
  },
  {
    name: 'zoom_4_skeleton',
    title: '100 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 13,
    maxZoom: 19,
    visible: false,
    layersType: 'skeleton',
    style: {
      id: [83717, 83718, 83719],
      width: 15,
      color: 'blue',
      widths: [11, 9, 5],
      colors: ['#002d70', '#0f51c1', '#578df1'],
    },
    selectedWidth: 8,
    selected: true,
    zoomSource: 'zoom_4',
    //zoomSource: 'road_4',
    source: 'zoom_4_skeleton',
  },

  {
    name: 'zoom_1_bridge',
    title: '>40mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 0,
    maxZoom: 8,
    visible: true,
    layersType: 'bridge',
    style: {
      id: [83717],
      width: 5,
      color: 'black',
      widths: [5],
      colors: ['#002d70'],
    },
    selectedWidth: 12,
    selected: true,
    zoomSource: 'zoom_1_bridge',
    source: 'zoom_1_bridge',
  },
  {
    name: 'zoom_2_bridge',
    title: '40mln-2mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 8,
    maxZoom: 10,
    visible: true,
    layersType: 'bridge',
    style: {
      id: [83717, 83718, 83719],
      width: 6,
      color: 'red',
      widths: [4, 2, 2],
      colors: ['#002d70', '#0f51c1', '#578df1'],
    },
    selectedWidth: 10,
    selected: true,
    zoomSource: 'zoom_2_bridge',
    source: 'zoom_2_bridge',
  },
  {
    name: 'zoom_3_bridge',
    title: '100 000 - 2 000 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 10,
    maxZoom: 18, //12.6,
    visible: true,
    layersType: 'bridge',
    style: {
      id: [83717, 83718, 83719],
      width: 11,
      color: 'green',
      widths: [7, 3, 2],
      colors: ['#002d70', '#0f51c1', '#578df1'],
    },
    selectedWidth: 9,
    selected: true,
    zoomSource: 'zoom_3_bridge',
    source: 'zoom_3_bridge',
  },

  //Старый вариант с прозрачным вектором для interaction ol
  // {
  //   name: 'zoom_1_roads', //'lyr_wfs_1z_road_>40_mln',
  //   title: '>40mln',
  //   group: 'wfs',
  //   type: 'wfs',
  //   minZoom: 2,
  //   maxZoom: undefined, //8.6,
  //   //style: { color: 'rgba(184,184,184, 0.01)', width: 10 },
  //   style: { color: 'black', width: 10 },
  //   selected: true,
  //   selectedWidth: 12,
  // },
  // {
  //   name: 'zoom_2_roads', //'lyr_wfs_2z_road_40_2_mln',
  //   title: '40mln-2mln',
  //   group: 'wfs',
  //   type: 'wfs',
  //   minZoom: 8.6,
  //   maxZoom: undefined, //9.4,
  //   //style: { color: 'rgba(184,184,184, 0.01)', width: 8 },
  //   style: { color: 'red', width: 8 },
  //   selected: true,
  //   selectedWidth: 10,
  // },
  // {
  //   name: 'zoom_3_roads', //'lyr_wfs_2z_road_100_min',
  //   title: '100 000 - 2 000 000',
  //   group: 'wfs',
  //   type: 'wfs',
  //   minZoom: 9.4,
  //   maxZoom: undefined, //12.6,
  //   //style: { color: 'rgba(184,184,184, 0.01)', width: 6 },
  //   style: { color: 'green', width: 6 },
  //   selected: true,
  //   selectedWidth: 9,
  // },
  // {
  //   name: 'zoom_4_roads', //'lyr_wfs_2z_road_2000_min',
  //   title: '100 000',
  //   group: 'wfs',
  //   type: 'wfs',
  //   minZoom: 12.6,
  //   maxZoom: undefined,
  //   //style: { color: 'rgba(184,184,184, 0.01)', width: 5 },
  //   style: { color: 'blue', width: 5 },
  //   selected: true,
  //   selectedWidth: 8,
  // },
];

const vectorLayers = [
  {
    name: 'zoom_1_category',
    title: '>40mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 0,
    maxZoom: 7,
    layersType: 'category',
    style: {
      widthId: [83717],
      widths: [5],
      widthColumn: 'value_of_the_road_gid',
      width: 5,
      color: '#cecece',
      colorId: [51845, 51846, 51847, 51848, 51849, 51850, 51851],
      colors: ['#910b20', '#910b20', '#910b20', '#d04532', '#f68c3b', '#f3d200', '#ffff52'],
      colorColumn: 'category_gid',
    },
    selectedWidth: 12,
    selected: true,
    source: 'zoom_1_category',
  },
  {
    name: 'zoom_2_category',
    title: '40mln-2mln',
    group: 'wfs',
    type: 'wfs',
    minZoom: 7,
    maxZoom: 9,
    layersType: 'road',
    style: {
      widthId: [83717, 83718, 83719],
      widths: [4, 2, 2],
      widthColumn: 'value_of_the_road_gid',
      width: 6,
      color: '#cecece',
      colorId: [51845, 51846, 51847, 51848, 51849, 51850, 51851],
      colors: ['#910b20', '#910b20', '#910b20', '#d04532', '#f68c3b', '#f3d200', '#ffff52'],
      colorColumn: 'category_gid',
    },
    selectedWidth: 10,
    selected: true,
    source: 'zoom_2_category',
  },
  {
    name: 'zoom_3_category',
    title: '100 000 - 2 000 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 9,
    maxZoom: 13, //12.6,
    layersType: 'road',
    style: {
      widthId: [83717, 83718, 83719],
      widths: [7, 3, 2],
      widthColumn: 'value_of_the_road_gid',
      width: 11,
      color: '#cecece',
      colorId: [51845, 51846, 51847, 51848, 51849, 51850, 51851],
      colors: ['#910b20', '#910b20', '#910b20', '#d04532', '#f68c3b', '#f3d200', '#ffff52'],
      colorColumn: 'category_gid',
    },
    selectedWidth: 9,
    selected: true,
    source: 'zoom_3_category',
  },
  {
    name: 'zoom_4_category',
    title: '100 000',
    group: 'wfs',
    type: 'wfs',
    minZoom: 13,
    maxZoom: 19,
    layersType: 'road',
    style: {
      widthId: [83717, 83718, 83719],
      widths: [11, 9, 5],
      widthColumn: 'value_of_the_road_gid',
      width: 15,
      color: '#cecece',
      colorId: [51845, 51846, 51847, 51848, 51849, 51850, 51851],
      colors: ['#910b20', '#910b20', '#910b20', '#d04532', '#f68c3b', '#f3d200', '#ffff52'],
      colorColumn: 'category_gid',
    },
    selectedWidth: 8,
    selected: true,
    source: 'zoom_4_category',
  },
];

const wmsRegionalSkeletonLayers = [
  {
    name: 'lyr_location_regions_shaded',
    title: 'Регионы, тень',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_regions_shaded', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: false,
    type: 'wms',
  },
  {
    name: 'lyr_location_regions_unshaded',
    title: 'Регионы, выделение',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_regions_unshaded', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: false,
    type: 'wms',
  },
  {
    name: 'lyr_road_by_value_shaded',
    title: 'Автомобильные дороги, тень',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_by_value_shaded', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: false,
    type: 'wms',
  },
  {
    name: 'lyr_road_conditions_skeleton_shaded',
    title: 'Участки опорной сети, тень',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: {
      LAYERS: 'lyr_road_conditions_skeleton_shaded',
      TILED: true,
      CRS: 'EPSG:3857',
      FORMAT: 'image/png8',
      gridSet: 'WebMercatorQuad',
    },
    visible: false,
    type: 'wms',
  },
];

const wmsTileLayers = [
  //-------Дороги

  {
    name: 'lyr_road_by_value',
    title: 'Автомобильные дороги',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_by_value', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    //params: { LAYERS: 'lyr_road_by_value', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Дороги',
    type: 'wms',
  },
  {
    name: 'lyr_road_conditions_skeleton',
    title: 'Участки опорной сети',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_skeleton', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Дороги',
    type: 'wms',
    filterField: 'value_of_the_road_gid',
    children: [
      {
        name: 'Федерального значения',
        code: 'lyr_road_conditions_skeleton_red',
        parent: 'lyr_road_conditions_skeleton',
        filterValue: '83717',
      },
      {
        name: 'Регионального значения',
        code: 'lyr_road_conditions_skeleton_blue',
        parent: 'lyr_road_conditions_skeleton',
        filterValue: '83718,83719',
      },
    ],
  },

  //-------Векторные слои--------

  {
    name: 'vec_lyr_road_by_value',
    title: 'Автомобильные дороги (вектор)',
    layerGroup: 'road',
    layerType: 'road',
    layerStyleType: 'simple',
    func: 'get_road_lr_geobox',
    visible: true,
    group: 'Дороги',
    source: 'road',
    geomType: 'line',
    type: 'vector',
    zoomLevels: [
      {
        zoomLayerGroup: 'zoom_1_lr',
        minZoom: 0,
        maxZoom: 7,
        styleLayers: [
          {
            styleLayerName: 'zoom_1_rgb',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717],
                widths: [5],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717],
                colors: ['#ce7b2b'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_2_lr',
        minZoom: 7,
        maxZoom: 9,
        styleLayers: [
          {
            styleLayerName: 'zoom_2_rgb',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [4, 2, 2],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_3_lr',
        minZoom: 9,
        maxZoom: 13,
        styleLayers: [
          {
            styleLayerName: 'zoom_3_rgb',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [7, 3, 2],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_4_lr',
        minZoom: 13,
        maxZoom: 19,
        styleLayers: [
          {
            styleLayerName: 'zoom_4_rgb',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [11, 9, 5],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#ce7b2b', '#e19b3c', '#f5bb4f'],
              },
            },
          },
        ],
      },
    ],
  },
  {
    name: 'vec_lyr_road_conditions_skeleton',
    title: 'Участки опорной сети (вектор)',
    layerGroup: 'skeleton',
    layerType: 'skeleton',
    layerStyleType: 'simple',
    func: 'get_road_lr_geobox',
    visible: false,
    group: 'Дороги',
    source: 'road',
    type: 'vector',
    geomType: 'line',
    zoomLevels: [
      {
        zoomLayerGroup: 'zoom_1_skeleton',
        minZoom: 0,
        maxZoom: 7,
        styleLayers: [
          {
            styleLayerName: 'zoom_1_skeleton_blue',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717],
                widths: [5],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717],
                colors: ['#002d70'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_2_skeleton',
        minZoom: 7,
        maxZoom: 9,
        styleLayers: [
          {
            styleLayerName: 'zoom_2_skeleton_blue',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [4, 2, 2],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#002d70', '#0f51c1', '#578df1'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_3_skeleton',
        minZoom: 9,
        maxZoom: 13,
        styleLayers: [
          {
            styleLayerName: 'zoom_3_skeleton_blue',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [7, 3, 2],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#002d70', '#0f51c1', '#578df1'],
              },
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_4_skeleton',
        minZoom: 13,
        maxZoom: 19,
        styleLayers: [
          {
            styleLayerName: 'zoom_1_skeleton_blue',
            style: {
              width_style: {
                width_column: 'value_of_the_road_gid',
                width_column_values: [83717, 83718, 83719],
                widths: [11, 9, 5],
              },
              color_style: {
                color_column: 'value_of_the_road_gid',
                color_column_values: [83717, 83718, 83719],
                colors: ['#002d70', '#0f51c1', '#578df1'],
              },
            },
          },
        ],
      },
    ],
  },

  //-------Конец -----Векторные слои--------

  //----------Графы----------------
  {
    name: 'lyr_graf_federal',
    title: 'Федерального значения',
    url: `${geoserverApiUrl}/graf/wms`,
    params: { LAYERS: 'lyr_graf_federal', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Граф дорог',
    type: 'wms',
  },
  {
    name: 'lyr_graf_regional',
    title: 'Регионального значения',
    url: `${geoserverApiUrl}/graf/wms`,
    params: { LAYERS: 'lyr_graf_regional', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Граф дорог',
    type: 'wms',
  },
  {
    name: 'lyr_graf_municipal',
    title: 'Местного значения',
    url: `${geoserverApiUrl}/graf/wms`,
    params: { LAYERS: 'lyr_graf_municipal', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Граф дорог',
    type: 'wms',
  },
  {
    name: 'lyr_graf_private_roads',
    title: 'Частные',
    url: `${geoserverApiUrl}/graf/wms`,
    params: { LAYERS: 'lyr_graf_private_roads', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Граф дорог',
    type: 'wms',
  },

  //-------Транспортная инфраструктура
  {
    name: 'lyr_transport_airfields',
    title: 'Аэропорты',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_transport_airfields', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },
  {
    name: 'lyr_transport_sea_ports',
    title: 'Морские порты',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_transport_sea_ports', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },
  {
    name: 'lyr_transport_river_ports',
    title: 'Речные порты',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_transport_river_ports', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },
  {
    name: 'lyr_transport_rails',
    title: 'Железнодорожные узлы',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_transport_rails', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },
  {
    name: 'lyr_other_border_points',
    title: 'Пограничные пункты',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_other_border_points', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },
  {
    name: 'lyr_ferry',
    title: 'Паромные переправы',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_ferry', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Транспортная инфраструктура',
    type: 'wms',
  },

  //------Состояние---
  {
    name: 'lyr_road_conditions_road_normative_condition',
    title: 'Нормативное состояние',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: {
      LAYERS: 'lyr_road_conditions_road_normative_condition',
      TILED: true,
      CRS: 'EPSG:3857',
      FORMAT: 'image/png8',
      gridSet: 'WebMercatorQuad',
    },
    visible: true,
    group: 'Состояние',
    type: 'wms',
    filterField: 'norm_percentage',
    children: [
      {
        name: 'Нормативное',
        code: 'lyr_road_conditions_road_normative_condition_normative',
        parent: 'lyr_road_conditions_road_normative_condition',
        filterValue: '>0.85',
      },
      {
        name: 'Ненормативное',
        code: 'lyr_road_conditions_road_normative_condition_nonormative',
        parent: 'lyr_road_conditions_road_normative_condition',
        filterValue: '<0.85',
      },
    ],
  },
  {
    name: 'lyr_road_conditions_overloaded',
    title: 'Участки перегрузки',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_overloaded', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Состояние',
    type: 'wms',
  },
  {
    name: 'lyr_diag_segment',
    title: 'Данные диагностики',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_diag_segment', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Состояние',
    type: 'wms',
  },
  // {
  //   name: 'lyr_road_flatness',
  //   title: 'Ровность',
  //   url: `${geoserverApiUrl}/skdf_open/wms`,
  //   params: { LAYERS: 'lyr_road_flatness', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
  //   group: 'Состояние',
  //   type: 'wms',
  // },

  {
    name: 'lyr_diag_hwd_eveness',
    title: 'Продольная ровность',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_diag_hwd_eveness', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Состояние',
    type: 'wms',
  },
  {
    name: 'lyr_diag_pavement_strength',
    title: 'Прочность дорожной одежды',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_diag_pavement_strength', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Состояние',
    type: 'wms',
  },

  //------Дорожная деятельность---
  {
    name: 'lyr_roadsworks_5y',
    title: 'Пятилетний план',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_roadsworks_5y', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Дорожная деятельность',
    type: 'wms',
    filterField: 'type_of_works_gid',
    children: [
      {
        name: 'Строительство и реконструкция',
        code: 'lyr_roadsworks_5y_building',
        parent: 'lyr_roadsworks_5y',
        filterValue: '83582,1693453',
      },
      {
        name: 'Капитальный ремонт',
        code: 'lyr_roadsworks_5y_capremont',
        parent: 'lyr_roadsworks_5y',
        filterValue: '83583,1693450',
      },
      { name: 'Ремонт', code: 'lyr_roadsworks_5y_remont', parent: 'lyr_roadsworks_5y', filterValue: '83584' },
      { name: 'Содержание', code: 'lyr_roadsworks_5y_maintenance', parent: 'lyr_roadsworks_5y', filterValue: '1665199' },
    ],
  },
  {
    name: 'lyr_roadworks_works',
    title: 'Участки проведения работ',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_roadworks_works', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Дорожная деятельность',
    type: 'wms',
    // filterField: 'lanes',
    range: { min: 2021, max: 2036, step: 1 },
  },
  {
    name: 'lyr_roadwork_warranty',
    title: 'Участки на гарантии',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_roadwork_warranty', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Дорожная деятельность',
    type: 'wms',
  },

  //-------Платность
  {
    name: 'lyr_toll',
    title: 'Платные участки',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_toll', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Платность',
    type: 'wms',
  },
  {
    name: 'lyr_toll_point',
    title: 'Пункты оплаты проезда',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_toll_point', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Платность',
    type: 'wms',
  },

  //--------Основные характеристики----
  {
    name: 'lyr_road_conditions_category',
    title: 'Техническая категория',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_category', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Основные характеристики',
    type: 'wms',
    filterField: 'category_gid',
    children: [
      { name: 'IА', code: 'lyr_road_conditions_category_IА', parent: 'lyr_road_conditions_category', filterValue: '51845' },
      { name: 'IБ', code: 'lyr_road_conditions_category_IБ', parent: 'lyr_road_conditions_category', filterValue: '51846' },
      { name: 'IВ', code: 'lyr_road_conditions_category_IВ', parent: 'lyr_road_conditions_category', filterValue: '51847' },
      { name: 'II', code: 'lyr_road_conditions_category_II', parent: 'lyr_road_conditions_category', filterValue: '51848' },
      { name: 'III', code: 'lyr_road_conditions_category_III', parent: 'lyr_road_conditions_category', filterValue: '51849' },
      { name: 'IV', code: 'lyr_road_conditions_category_IV', parent: 'lyr_road_conditions_category', filterValue: '51850' },
      { name: 'V', code: 'lyr_road_conditions_category_V', parent: 'lyr_road_conditions_category', filterValue: '51851' },
    ],
  },
  {
    name: 'lyr_road_conditions_lanes',
    title: 'Число полос движения, шт',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_lanes', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Основные характеристики',
    type: 'wms',
    filterField: 'lanes',
    range: { min: 1, max: 10, step: 1, stepCount: 5 },
  },
  {
    name: 'lyr_road_conditions_os',
    title: 'Нагрузка на ось, тонн/ось',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_os', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Основные характеристики',
    type: 'wms',
    filterField: 'os',
    children: [
      {
        name: '6',
        code: 'lyr_road_conditions_os_6',
        parent: 'lyr_road_conditions_os',
        //filterValue: '1553237',
        filterValue: '6',
      },
      { name: '10', code: 'lyr_road_conditions_os_10', parent: 'lyr_road_conditions_os', filterValue: '10' },
      { name: '11.5', code: 'lyr_road_conditions_os_11', parent: 'lyr_road_conditions_os', filterValue: '11.5' },
    ],
  },

  //--------Динамические  характеристики----
  {
    name: 'lyr_road_conditions_top_speed',
    title: 'Максимальная скорость, км/ч',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_top_speed', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Динамические  характеристики',
    type: 'wms',
    filterField: 'top_speed',
    range: { min: 5, max: 130, step: 5, stepCount: 6 },
  },
  {
    name: 'lyr_road_conditions_capacity',
    title: 'Пропускная способность',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_capacity', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Динамические  характеристики',
    type: 'wms',
    filterField: 'capacity',
    range: { min: 0, max: 100000, step: 10000, stepCount: 5 },
  },
  {
    name: 'lyr_road_conditions_traffic',
    title: 'Интенсивность движения',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_traffic', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Динамические  характеристики',
    type: 'wms',
    filterField: 'traffic',
    range: { min: 0, max: 100000, step: 10000, stepCount: 5 },
  },

  //--------Другие характеристики----
  {
    name: 'lyr_road_conditions_category_sp',
    title: 'Категория по СП 42.13330',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_category_sp', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Другие характеристики',
    type: 'wms',
    filterField: 'category_snip_gid',
    children: [
      // {
      //   name: 'Магистральные дороги',
      //   code: 'lyr_road_conditions_category_sp_trunk_roads',
      //   parent: 'lyr_road_conditions_category_sp',
      //   filterValue: '1643508,1643509',
      // },
      // {
      //   name: 'Магистральные улицы',
      //   code: 'lyr_road_conditions_category_sp_trunk_street',
      //   parent: 'lyr_road_conditions_category_sp',
      //   filterValue: '1643510,1643511,1643512,1643513',
      // },
      // {
      //   name: 'Улицы и дороги местного значения',
      //   code: 'lyr_road_conditions_category_sp_local_street',
      //   parent: 'lyr_road_conditions_category_sp',
      //   filterValue: '1643514,1643517,1643518,1643519,1643525,1643526,1643527',
      // },
      {
        name: 'Магистральные городские дороги',
        code: 'lyr_road_conditions_category_sp_trunk_roads',
        parent: 'lyr_road_conditions_category_sp',
        filterValue: '1643508,1643509',
      },
      {
        name: 'Магистральные улицы общегородского значения',
        code: 'lyr_road_conditions_category_sp_trunk_street',
        parent: 'lyr_road_conditions_category_sp',
        filterValue: '1643510,1643511,1643512',
      },
      {
        name: 'Магистральные улицы районного значения',
        code: 'lyr_road_conditions_category_sp_trunk_street_district',
        parent: 'lyr_road_conditions_category_sp',
        filterValue: '1643513',
      },
      {
        name: 'Улицы и дороги местного значения',
        code: 'lyr_road_conditions_category_sp_local_street',
        parent: 'lyr_road_conditions_category_sp',
        filterValue: '1643514,1643518,1643519,1643525,1643526,1643527',
      },
      {
        name: 'Пешеходные улицы и площади',
        code: 'lyr_road_conditions_category_sp_local_walkstreet',
        parent: 'lyr_road_conditions_category_sp',
        filterValue: '1643517',
      },
    ],
  },
  {
    name: 'lyr_roadway_width',
    title: 'Ширина проезжей части, м',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_roadway_width', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Другие характеристики',
    type: 'wms',
    filterField: 'roadway_width',
    range: { min: 2.75, max: 45, step: 0.05, stepCount: 4 },
  },
  {
    name: 'lyr_roadbed_width',
    title: 'Ширина земляного полотна, м',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_roadbed_width', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Другие характеристики',
    type: 'wms',
    filterField: 'roadbed_width',
    range: { min: 2.75, max: 52.5, step: 0.05, stepCount: 4 },
  },
  {
    name: 'lyr_road_conditions_coating',
    title: 'Вид покрытия',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_coating', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Другие характеристики',
    type: 'wms',
    filterField: 'coating_gid',
    children: [
      {
        name: 'Капитальный',
        code: 'lyr_road_conditions_coating_capital',
        parent: 'lyr_road_conditions_coating',
        filterValue: '51834,51835,51836,1643500,2041356,2041399,51833',
      },
      {
        name: 'Переходный',
        code: 'lyr_road_conditions_coating_transition',
        parent: 'lyr_road_conditions_coating',
        filterValue: '51838,1643484,1643501',
      },
      { name: 'Облегченный', code: 'lyr_road_conditions_coating_lightweight', parent: 'lyr_road_conditions_coating', filterValue: '51837' },
      {
        name: 'Низший',
        code: 'lyr_road_conditions_coating_lower',
        parent: 'lyr_road_conditions_coating',
        filterValue: '51839,1643483,2041355',
      },
    ],
  },
  {
    name: 'lyr_road_conditions_class',
    title: 'Класс',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_conditions_class', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Другие характеристики',
    type: 'wms',
    filterField: 'class_of_road_gid',
    children: [
      { name: 'Автомагистраль', code: 'lyr_road_conditions_class_highway', parent: 'lyr_road_conditions_class', filterValue: '1643179' },
      {
        name: 'Скоростная автомобильная дорога',
        code: 'lyr_road_conditions_class_highspeed',
        parent: 'lyr_road_conditions_class',
        filterValue: '1643177',
      },
      {
        name: 'Нескоростная автомобильная дорога',
        code: 'lyr_road_conditions_coating_lower_nohighspeed',
        parent: 'lyr_road_conditions_class',
        filterValue: '1643178',
      },
    ],
  },

  // {
  //   name: 'lyr_road_conditions_limited',
  //   title: 'Ограничения для перевозки тяжеловесных и крупногабаратных грузов',
  //   url: `${geoserverApiUrl}/skdf_open/wms',
  //   params: { LAYERS: 'lyr_road_conditions_limited', TILED: true, CRS: 'EPSG:3857', FORMAT:'image/png8' },
  //   group: 'Технические характеристики',
  //   type: 'wms',
  // },

  //------Искусственные сооружения----
  {
    name: 'vec_lyr_bridges',
    title: 'Мостовые сооружения (вектор)',
    layerGroup: 'bridge',
    layerType: 'bridge',
    layerStyleType: 'simple',
    func: 'get_bridge_geobox',
    visible: false,
    group: 'Искусственные сооружения',
    source: 'bridge',
    geomType: 'point',
    type: 'vector',
    zoomLevels: [
      {
        zoomLayerGroup: 'zoom_1_bridge',
        minZoom: 0,
        maxZoom: 8,
        styleLayers: [
          {
            styleLayerName: 'zoom_1_bridge_svg',
            style: {
              color: 'black',
              width: 10,
              svg: '<svg width="24" fill="none" height="24" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" rx="4" fill="#4378DD"/><path d="M20.333 5.333H3.667V7h16.666V5.333ZM3.667 12V7.833h16.666V12a2.5 2.5 0 0 0-2.5 2.5v4.167H14.5V14.5a2.5 2.5 0 0 0-5 0v4.167H6.167V14.5a2.5 2.5 0 0 0-2.5-2.5Z" fill="#FBFBFB"/></svg>',
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_2_bridge',
        minZoom: 8,
        maxZoom: 10,
        styleLayers: [
          {
            styleLayerName: 'zoom_2_bridge_svg',
            style: {
              color: 'black',
              width: 10,
              svg: '<svg width="24" fill="none" height="24" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" rx="4" fill="#4378DD"/><path d="M20.333 5.333H3.667V7h16.666V5.333ZM3.667 12V7.833h16.666V12a2.5 2.5 0 0 0-2.5 2.5v4.167H14.5V14.5a2.5 2.5 0 0 0-5 0v4.167H6.167V14.5a2.5 2.5 0 0 0-2.5-2.5Z" fill="#FBFBFB"/></svg>',
            },
          },
        ],
      },
      {
        zoomLayerGroup: 'zoom_3_bridge',
        minZoom: 10,
        maxZoom: 18,
        styleLayers: [
          {
            styleLayerName: 'zoom_3_bridge_svg',
            style: {
              color: 'green',
              width: 10,
              svg: '<svg width="24" fill="none" height="24" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" rx="4" fill="#4378DD"/><path d="M20.333 5.333H3.667V7h16.666V5.333ZM3.667 12V7.833h16.666V12a2.5 2.5 0 0 0-2.5 2.5v4.167H14.5V14.5a2.5 2.5 0 0 0-5 0v4.167H6.167V14.5a2.5 2.5 0 0 0-2.5-2.5Z" fill="#FBFBFB"/></svg>',
            },
          },
        ],
      },
    ],
  },
  {
    name: 'lyr_bridges',
    title: 'Мостовые сооружения',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_bridges', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Искусственные сооружения',
    type: 'wms',
  },
  {
    name: 'lyr_tunnels',
    title: 'Тоннели',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_tunnels', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Искусственные сооружения',
    type: 'wms',
  },
  {
    name: 'lyr_eng_pipes',
    title: 'Трубы',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_eng_pipes', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Искусственные сооружения',
    type: 'wms',
  },

  //------Безопасность----
  {
    name: 'lyr_road_emergency_section',
    title: 'Аварийно-опасные участки',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_emergency_section', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Безопасность',
    type: 'wms',
  },
  {
    name: 'lyr_road_accidents',
    title: 'ДТП',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_road_accidents', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Безопасность',
    type: 'wms',
  },
  {
    name: 'lyr_weight_control_points',
    title: 'ПВГК',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_weight_control_points', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Безопасность',
    type: 'wms',
  },

  //------Обустройство----
  {
    name: 'lyr_eng_lighting',
    title: 'Освещение',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_eng_lighting', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Элементы обустройства',
    type: 'wms',
  },
  {
    name: 'lyr_eng_km_posts',
    title: 'Километровые знаки',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_eng_km_posts', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Элементы обустройства',
    type: 'wms',
  },
  {
    name: 'lyr_eng_traffic_lights',
    title: 'Светофоры',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_eng_traffic_lights', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Элементы обустройства',
    type: 'wms',
  },
  {
    name: 'lyr_srv_bus_stops',
    title: 'Остановки',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_srv_bus_stops', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Элементы обустройства',
    type: 'wms',
  },
  {
    name: 'lyr_eng_crosswalks',
    title: 'Пешеходные переходы',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_eng_crosswalks', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Элементы обустройства',
    type: 'wms',
  },
  {
    name: 'lyr_srv_gas_stations',
    title: 'АЗС',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_srv_gas_stations', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Объекты дорожного сервиса',
    type: 'wms',
  },
  {
    name: 'lyr_srv_service_stations',
    title: 'СТО',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_srv_service_stations', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    //group: 'Обустройство',
    group: 'Объекты дорожного сервиса',
    type: 'wms',
  },

  //------Местоположение----
  {
    name: 'lyr_location_regions',
    title: 'Регионы',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_regions', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Местоположение',
    type: 'wms',
  },
  {
    name: 'lyr_location_agglomerations',
    title: 'Агломерации',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_agglomerations', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Местоположение',
    type: 'wms',
  },
  {
    name: 'lyr_location_regions_mo',
    title: 'Мун. образования',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_regions_mo', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Местоположение',
    type: 'wms',
  },
  {
    name: 'lyr_location_climate_zones',
    title: 'Дорожно-климатические зоны',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_location_climate_zones', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Местоположение',
    type: 'wms',
    filterField: 'climatic_zone_gid',
    children: [
      { name: 'I', code: 'lyr_location_climate_zones_I', parent: 'lyr_location_climate_zones', filterValue: '1663788' },
      { name: 'II', code: 'lyr_location_climate_zones_II', parent: 'lyr_location_climate_zones', filterValue: '1663789' },
      { name: 'III', code: 'lyr_location_climate_zones_III', parent: 'lyr_location_climate_zones', filterValue: '1663790' },
      { name: 'IV', code: 'lyr_location_climate_zones_IV', parent: 'lyr_location_climate_zones', filterValue: '1663791' },
      { name: 'V', code: 'lyr_location_climate_zones_V', parent: 'lyr_location_climate_zones', filterValue: '1663792' },
    ],
  },
  {
    name: 'caddivsion',
    title: 'Единицы кад. деления',
    url: 'https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/tile/{z}/{y}/{x}.pbf',
    params: { style: 'https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/resources/styles/root.json' },
    visible: true,
    group: 'Местоположение',
    type: 'pbf',
    layerFilterType: '',
  },
  //------Общественный контроль----
  {
    name: 'lyr_messages',
    title: 'Сообщения граждан',
    url: `${geoserverApiUrl}/skdf_open/wms`,
    params: { LAYERS: 'lyr_messages', TILED: true, CRS: 'EPSG:3857', FORMAT: 'image/png8', gridSet: 'WebMercatorQuad' },
    visible: true,
    group: 'Общественный контроль',
    type: 'wms',
  },

  // //-------Росреестр-------

  // {
  //   name: 'caddivsion',
  //   title: 'Единицы кадастрового деления',
  //   url: 'https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/tile/{z}/{y}/{x}.pbf',
  //   params: { style: 'https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/resources/styles/root.json' },
  //   group: 'Росреестр',
  //   type: 'pbf',
  //   layerFilterType: '',
  // },
  // {
  //   name: 'show:4,3,2,1',
  //   title: 'Зоны с особыми условиями использования территории',
  //   url: 'https://pkk.rosreestr.ru/arcgis/rest/services/PKK6/ZONES/MapServer/export?_ts=false',
  //   //url: 'http://pkk5.rosreestr.ru/arcgis/rest/services/PKK6/ZONES/MapServer/export?_ts=false',
  //   //url: 'api-rosreestr/arcgis/rest/services/PKK6/ZONES/MapServer/export?_ts=false',
  //   //params: { LAYERS: 'show:4,3,2,1', DPI: 96, TRANSPARENT: true, SIZE: '1024,1024' },
  //   params: { LAYERS: 'show:4,3,2,1' },
  //   group: 'Росреестр',
  //   type: 'mapservice',
  //   layerFilterType: '',
  // },
];

export { baseMapLayers, wmsTileLayers, wfsLayers, wfsHoverLayers, vectorLayers, wmsRegionalSkeletonLayers };
